# Generated by Django 3.2.19 on 2023-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
