# Generated by Django 3.2.19 on 2023-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_alter_store_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
