# Generated by Django 3.2.19 on 2023-06-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_store_owner'),
        ('Stores', '0003_alter_store_bio'),
    ]

    operations = [
    ]
