# Generated by Django 3.2.19 on 2023-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('sold_amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rate_number', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('other', 'Other'), ('cloth', 'Cloth'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('electronic', 'Electronic'), ('furniture', 'furniture')], default='other', max_length=20)),
            ],
        ),
    ]
